class Data:
    linkIdentifier = "a[href]"
    buttonIdentifier = ".button"
    regFirstNameField = "[name='customer.firstName']"
    regLastNameField = "[name='customer.lastName']"
    regStreetField = "[name='customer.address.street']"
    regCityField = "[name='customer.address.city']"
    regStateField = "[name='customer.address.state']"
    regZipCodeField = "[name='customer.address.zipCode']"
    regPhoneNumberField = "[name='customer.phoneNumber']"
    regSSNField = "[name='customer.ssn']"
    regUsernameField = "[name='customer.username']"
    regPasswordField = "[name='customer.password']"
    confirmPasswordField = "[name='repeatedPassword']"
    regPageTitle = ".title"
    regPageTitleText = "Signing up is easy!"
    regFormFields = ".form2 input.input"
    regFirstName = "[name='customer.firstName']"
    URL = "https://parabank.parasoft.com/"
    registerLink = "[href='register.htm']"
    registerButton = ".form2 input.button"
    logoutLink = "[href='logout.htm']"
    loginUsernameField = "[name='username']"
    loginPasswordField = "[name='password']"
    loginButton = ".login>input.button"
    loginError = ".error"
    accountOpeningLink = "[href='openaccount.htm']"
    submitButton = "input.button"
    accountOptions = "select#type"
    accountNumber = "select#fromAccountId"
    transferFundsLink = "[href='transfer.htm']"
    amountField = "input#amount"
    newAccountLink = "#newAccountId"
    requestLoanLink = "[href='requestloan.htm']"
    loanAmountField = "input#amount"
    downPaymentField = "input#downPayment"
    loginTitle = "#leftPanel>h2"
