name: SeamlessHR CLI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run Assessment Tests
        run: |
          behave -f behave_html_formatter:HTMLFormatter -o reports/report.html

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/

